name: Maha_ODD
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libstdcxx-ng=9.1.0
  - ncurses=6.3
  - openssl=1.1.1m
  - pip=21.2.2
  - python=3.7.11
  - readline=8.1.2
  - setuptools=58.0.4
  - sqlite=3.37.0
  - tk=8.6.11
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - absl-py==0.9.0
    - aiohttp==3.6.2
    - alembic==1.3.1
    - annoy==1.16.3
    - astor==0.8.1
    - async-timeout==3.0.1
    - attrs==21.4.0
    - beautifulsoup4==4.9.0
    - blessings==1.7
    - boto3==1.12.38
    - botocore==1.15.38
    - cachetools==4.0.0
    - chardet==3.0.4
    - click==8.0.3
    - cliff==3.1.0
    - cloudpickle==2.0.0
    - cmaes==0.4.0
    - cmd2==0.8.9
    - colorama==0.4.3
    - colorlog==4.1.0
    - configparser==5.0.0
    - databricks-cli==0.10.0
    - docker==4.2.0
    - docopt==0.6.2
    - docutils==0.15.2
    - entrypoints==0.3
    - filelock==3.0.12
    - flask==1.1.2
    - future==0.18.2
    - gitdb==4.0.2
    - gitpython==3.1.0
    - google==2.0.3
    - google-auth==1.13.1
    - google-auth-oauthlib==0.4.1
    - gorilla==0.3.0
    - gpustat==0.6.0
    - grpcio==1.28.1
    - gunicorn==20.0.4
    - hydra-core==0.11.3
    - idna==2.9
    - importlib-metadata==4.10.0
    - importlib-resources==5.4.0
    - iniconfig==1.1.1
    - itsdangerous==1.1.0
    - jinja2==3.0.3
    - jmespath==0.9.5
    - joblib==1.1.0
    - jsonschema==4.4.0
    - mako==1.1.0
    - markdown==3.2.1
    - markupsafe==2.0.1
    - mlflow==1.7.2
    - multidict==4.7.5
    - nltk==3.6.7
    - nose==1.3.7
    - numpy==1.21.5
    - nvidia-ml-py3==7.352.0
    - oauthlib==3.1.0
    - omegaconf==1.4.1
    - optuna==1.3.0
    - packaging==21.3
    - pandas==1.3.5
    - pbr==5.4.5
    - pillow==7.1.1
    - pluggy==1.0.0
    - prettytable==0.7.2
    - prometheus-client==0.12.0
    - prometheus-flask-exporter==0.13.0
    - protobuf==3.11.3
    - psutil==5.9.0
    - py==1.11.0
    - py-spy==0.3.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydevd-pycharm==201.6668.115
    - pyparsing==3.0.6
    - pyperclip==1.8.0
    - pyrsistent==0.18.1
    - pytest==6.2.5
    - python-dateutil==2.8.2
    - python-editor==1.0.4
    - pytorch-lightning==0.7.3
    - pytorch-transformers==1.2.0
    - pytz==2021.3
    - pyyaml==5.3.1
    - querystring-parser==1.2.4
    - ray==0.8.4
    - redis==3.4.1
    - regex==2021.11.10
    - requests==2.23.0
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - s3transfer==0.3.3
    - sacremoses==0.0.38
    - scikit-learn==0.22.2.post1
    - scipy==1.7.3
    - sentencepiece==0.1.85
    - simplejson==3.17.0
    - six==1.16.0
    - smmap==3.0.1
    - soupsieve==2.0
    - sqlalchemy==1.3.11
    - sqlparse==0.3.1
    - stevedore==1.32.0
    - sweeper==0.9.0
    - tabulate==0.8.7
    - tensorboard==2.2.0
    - tensorboard-plugin-wit==1.6.0.post3
    - tensorly==0.4.5
    - tokenizers==0.5.2
    - toml==0.10.2
    - torch==1.3.1
    - torchvision==0.4.2
    - tqdm==4.45.0
    - transformers==2.8.0
    - typing-extensions==4.0.1
    - urllib3==1.25.8
    - wcwidth==0.2.5
    - websocket-client==0.57.0
    - werkzeug==1.0.1
    - yarl==1.4.2
    - zipp==3.7.0

